stages:
  - test
  - build
  - deploy

unit-test-job:
  stage: test
  tags:
    - rust
  script:
    - cargo test

build-job:
  stage: build
  tags:
    - rust
  script:
    - cargo build --release

deploy-job:
  stage: deploy
  tags:
    - rust
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+\-release/'
  environment: production
  script:
    - cargo publish
