stages:
  - test
  - deploy

unit-test-job:
  stage: test
  tags:
    - rust
  script:
    - cargo clippy -- --deny clippy:pedantic
    - cargo test

linting-test-job:
  before_script:
    - rustup component add clippy
    - rustup component add rustfmt
  script:
    - cargo fmt --all -- --check
    - cargo clippy -- --deny clippy::pedantic

deploy-job:
  stage: deploy
  tags:
    - rust
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+\-release/'
  environment: production
  script:
    - cargo login $CARGO_REGISTRY_TOKEN
    - cargo publish
