name: Release candidate testing & linting

on:
  push:
    tags:
      - 'v*.*.*-rc*'

env:
  CARGO_TERM_COLOR: always

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - name: Setup clippy & fmt
      run: |
        rustup component add clippy
        rustup component add rustfmt

    - name: lint with clippy
      run: cargo clippy -- --deny clippy:pedantic

    - name: check formatting
      run: cargo fmt --all -- --check

  testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - name: Run tests
      run: cargo test
