name: Crates IO deployment release

on:
  push:
    tags:
      - 'v*.*.*-release'

env:
  CARGO_TERM_COLOR: always

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - name: Setup clippy & fmt
      run: |
        rustup component add clippy
        rustup component add rustfmt

    - name: lint with clippy
      run: cargo clippy -- --deny clippy:pedantic

    - name: check formatting
      run: cargo fmt --all -- --check

  testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - name: Run tests
      run: cargo test


  push-to-crates-io:
    needs: [linting, testing]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - name: Push release to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        export CARGO_REGISTRY_TOKEN="$CARGO_REGISTRY_TOKEN"
        cargo publish
